// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import DarkModeController from "./dark_mode_controller"
application.register("dark-mode", DarkModeController)

import FlashController from "./flash_controller"
application.register("flash", FlashController)

import setupUltimateTurboModal from "ultimate_turbo_modal";
setupUltimateTurboModal(application);
